### ISSUE TITLE
Proposal: stop wrapping code samples

### ISSUE THREAD

**Issue by willshowell** [angular/material.angular.io#236]
Wrapping for the code examples was added in #95, but I can't find any conversations about it and would like to just suggest not wrapping them. Personally, I think the x-scroll behavior on Github is nice,

```scss
pre {
  // Pre elements won't wrap text by default and can exceed the boundaries of their parent element.
  // This adds extra scroll space when visiting the docs mobile. Pre-wrapping the code examples
  // will ensure that the code never exceeds the page width.
  white-space: pre-wrap;
}
```

For some examples, the wrapping makes the code impossible to read:

![screen shot 2017-08-09 at 12 13 43 pm](https://user-images.githubusercontent.com/6475576/29131900-53063dc0-7cfc-11e7-85d7-5a0a459ee069.png)

whereas without wrapping, you can read the code formatted in the way it was intended:

![screen shot 2017-08-09 at 12 15 13 pm](https://user-images.githubusercontent.com/6475576/29131935-79f84b6c-7cfc-11e7-8841-549810803536.png)
